"""empty message

Revision ID: 18889e964c62
Revises: 1c9e8c2e3f1a
Create Date: 2026-02-02 18:27:42.907029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18889e964c62'
down_revision = '1c9e8c2e3f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_anon',
    sa.Column('anon_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('anon_user_id')
    )
    op.create_table('attempts',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('anon_user_id', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('module_id', sa.String(length=100), nullable=False),
    sa.Column('threshold_percent', sa.SmallInteger(), nullable=False),
    sa.Column('max_cycles_allowed', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.String(length=20), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("end_reason IN ('passed','max_cycles','abandoned','system_error')", name='ck_attempts_end_reason'),
    sa.ForeignKeyConstraint(['anon_user_id'], ['users_anon.anon_user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index('idx_attempts_anon_user_id', ['anon_user_id'], unique=False)
        batch_op.create_index('idx_attempts_last_activity_at', ['last_activity_at'], unique=False)
        batch_op.create_index('idx_attempts_module_id', ['module_id'], unique=False)

    op.create_table('cycles',
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_index', sa.SmallInteger(), nullable=False),
    sa.Column('quiz_id', sa.String(length=100), nullable=False),
    sa.Column('quiz_type', sa.String(length=20), nullable=False),
    sa.Column('quiz_submitted_at', sa.DateTime(), nullable=False),
    sa.Column('score_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('passed_threshold', sa.Boolean(), nullable=False),
    sa.Column('diagnosis_at', sa.DateTime(), nullable=True),
    sa.Column('diagnosis_model_name', sa.String(length=100), nullable=True),
    sa.Column('diagnosed_concept_ids', sa.JSON(), nullable=True),
    sa.Column('intervention_issued_at', sa.DateTime(), nullable=True),
    sa.Column('lesson_concept_ids', sa.JSON(), nullable=True),
    sa.Column('micro_lesson_count', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("quiz_type IN ('diagnostic','remedial')", name='ck_cycles_quiz_type'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('cycle_id'),
    sa.UniqueConstraint('attempt_id', 'cycle_index', name='uq_cycle_attempt_index')
    )
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.create_index('idx_cycles_attempt_id', ['attempt_id'], unique=False)
        batch_op.create_index('idx_cycles_quiz_type', ['quiz_type'], unique=False)
        batch_op.create_index('idx_cycles_submitted_at', ['quiz_submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycles', schema=None) as batch_op:
        batch_op.drop_index('idx_cycles_submitted_at')
        batch_op.drop_index('idx_cycles_quiz_type')
        batch_op.drop_index('idx_cycles_attempt_id')

    op.drop_table('cycles')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_attempts_module_id')
        batch_op.drop_index('idx_attempts_last_activity_at')
        batch_op.drop_index('idx_attempts_anon_user_id')

    op.drop_table('attempts')
    op.drop_table('users_anon')
    # ### end Alembic commands ###
